name: Testing Site
favicon: null
layout_spectrum: 1
typography_spectrum: 0.28858
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#263204'
    - '#4b5a00'
    - '#c7a720'
    - '#ddd63a'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
